### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by NoLectureNote** [facebookresearch/llama-recipes#16]
I'm trying to fine-tune llama2-13b with 4*A100 80G on aws,  I installed requiements.txt already , but  nvidia-smi  is CUDA Version: 11.2.  Is the RuntimeError related to cuda version?

`LD_LIBRARY_PATH=/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/lib/:$LD_LIBRARY_PATH  CUDA_VISIBLE_DEVICES=0,1,3 torchrun --nnodes 1 --nproc_per_node 3  ./llama_finetuning.py --enable_fsdp --model_name /home/ts/models/Llama-2-13b-chat-hf --use_peft --peft_method lora --output_dir /home/ts/work/shaohaiming/llama-recipes/output/PEFT --dist_checkpoint_root_folder /home/ts/work/shaohaiming/llama-recipes/output/FSDP --use_fp16 --save_model
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/ts/miniconda3/envs/llama2 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.0/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Loading binary /home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/ts/miniconda3/envs/llama2 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.0/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Loading binary /home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so...
bin /home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/ts/miniconda3/envs/llama2 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.0/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Loading binary /home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so...
--> Running with torch dist debug set to detail
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.68s/it]
--> Model /home/ts/models/Llama-2-13b-chat-hf

--> /home/ts/models/Llama-2-13b-chat-hf has 13015.86432 Million params

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.72s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.71s/it]
trainable params: 6,553,600 || all params: 13,022,417,920 || trainable%: 0.05032552357220002
FP16 enabled
trainable params: 6,553,600 || all params: 13,022,417,920 || trainable%: 0.05032552357220002
trainable params: 6,553,600 || all params: 13,022,417,920 || trainable%: 0.05032552357220002
--> applying fdsp activation checkpointing...
Found cached dataset csv (/home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-abd39d944ed316eb.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-08f3a4087d2592f5.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-eb83d3d0988f7eb7.arrow
--> Training Set Length = 154675
Found cached dataset csv (/home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-55b469f8ce4636aa.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-5d8415cc119fe61f.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-021757ce16db014b.arrow
--> Validation Set Length = 7060
/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Training Epoch0:   0%|                                                                                                                           | 0/12889 [00:00<?, ?it/s]--> applying fdsp activation checkpointing...
--> applying fdsp activation checkpointing...
Found cached dataset csv (/home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-abd39d944ed316eb.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-08f3a4087d2592f5.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-eb83d3d0988f7eb7.arrow
Found cached dataset csv (/home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-55b469f8ce4636aa.arrow
Found cached dataset csv (/home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-5d8415cc119fe61f.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-021757ce16db014b.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-abd39d944ed316eb.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-08f3a4087d2592f5.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-eb83d3d0988f7eb7.arrow
Found cached dataset csv (/home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-55b469f8ce4636aa.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-5d8415cc119fe61f.arrow
Loading cached processed dataset at /home/ts/work/shaohaiming/llama-recipes/cache_data/csv/samsum-43bab4d22b1186c1/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d/cache-021757ce16db014b.arrow
/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Training Epoch0:   0%|                                                                                                                           | 0/12889 [00:00<?, ?it/s]/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/cuda/memory.py:303: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Training Epoch0:   0%|                                                                                                                           | 0/12889 [00:04<?, ?it/s]
Training Epoch0:   0%|                                                                                                                           | 0/12889 [00:03<?, ?it/s]
Training Epoch0:   0%|                                                                                                                           | 0/12889 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/ts/work/shaohaiming/llama-recipes/./llama_finetuning.py", line 239, in <module>
    fire.Fire(main)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ts/work/shaohaiming/llama-recipes/./llama_finetuning.py", line 222, in main
    results = train(
  File "/home/ts/work/shaohaiming/llama-recipes/utils/train_utils.py", line 98, in train
    scaler.scale(loss).backward()
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/home/ts/work/shaohaiming/llama-recipes/./llama_finetuning.py", line 239, in <module>
    fire.Fire(main)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
Traceback (most recent call last):
  File "/home/ts/work/shaohaiming/llama-recipes/./llama_finetuning.py", line 239, in <module>
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    fire.Fire(main)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component = fn(*varargs, **kwargs)
  File "/home/ts/work/shaohaiming/llama-recipes/./llama_finetuning.py", line 222, in main
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    results = train(
  File "/home/ts/work/shaohaiming/llama-recipes/utils/train_utils.py", line 98, in train
    scaler.scale(loss).backward()
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    torch.autograd.backward(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    component = fn(*varargs, **kwargs)
RuntimeError  File "/home/ts/work/shaohaiming/llama-recipes/./llama_finetuning.py", line 222, in main
: element 0 of tensors does not require grad and does not have a grad_fn
    results = train(
  File "/home/ts/work/shaohaiming/llama-recipes/utils/train_utils.py", line 98, in train
    scaler.scale(loss).backward()
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 36331) of binary: /home/ts/miniconda3/envs/llama2/bin/python
Traceback (most recent call last):
  File "/home/ts/miniconda3/envs/llama2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ts/miniconda3/envs/llama2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./llama_finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-20_18:21:55
  host      : iZ6wecshuj1ifmxy70w4zpZ
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 36332)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-07-20_18:21:55
  host      : iZ6wecshuj1ifmxy70w4zpZ
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 36334)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-20_18:21:55
  host      : iZ6wecshuj1ifmxy70w4zpZ
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 36331)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

**Comment by chauhang** [comment]
@NoLectureNote Can you please test with CUDA 11.8? Also see this https://github.com/facebookresearch/llama-recipes/issues/5#issuecomment-1643088818
