### ISSUE TITLE
torch distribution  port 

### ISSUE THREAD

**Issue by cdhx** [facebookresearch/llama-recipes#186]
### System Info

torch 2.0.1
GPU  v100*4

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

```
# official script, i am sure it is correct 
torchrun --nnodes 1 --nproc_per_node 4  examples/finetuning.py --enable_fsdp --model_name /home/xhuang/llama-recipes-main/model_hf/7B/ --use_peft --peft_method lora --dataset alpaca_dataset  --save_model --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --pure_bf16 --output_dir /home/xhuang/llama-recipes-main/PEFT/model

```

### Error logs

```

WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/home/xhuang/.conda/envs/llama/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 692, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

```

### Expected behavior

If only one program is running, there is no problem at all, 

but if one program is already running, running another one will cause a port conflict

**Comment by HamidShojanazeri** [comment]
@cdhx when you are running torchrun it uses a default port so once its running can not run the second one unless you specify a new port to that `--rdzv_endpoint`

**Comment by cdhx** [comment]
it does not work

i tried this command

```
torchrun --nnodes 1 --nproc_per_node 2  examples/finetuning.py --enable_fsdp --model_name  model_hf/7B/ --use_peft --peft_method lora --dataset pyql_dataset  --save_model --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --pure_bf16 --output_dir PEFT/pyql --rdzv_endpoint 30000  
```

and got

```

WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home2/xhuang/.conda/envs/llama/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 216, in launch_agent
    master_addr, master_port = _get_addr_and_port(rdzv_parameters)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 172, in _get_addr_and_port
    raise ValueError(
ValueError: port is missing in endpoint: 30000. Try to specify --master-port
```

so I specify --master-port
```
torchrun --nnodes 1 --nproc_per_node 2  examples/finetuning.py --enable_fsdp --model_name  model_hf/7B/ --use_peft --peft_method lora --dataset pyql_dataset  --save_model --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --pure_bf16 --output_dir PEFT/pyql --rdzv_endpoint 30000  ---master-port 30000
```
and got 
```

WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/home2/xhuang/.conda/envs/llama/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 858, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 692, in _initialize_workers
    self._rendezvous(worker_group)
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/xhuang/.conda/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

```

**Comment by polym** [comment]
We should put `--rdzv_endpoint` before `examples/finetuning.py`, otherwise,  `--rdzv_endpoint` will be treat as parameters of `examples/finetuning.py` 

```shell
torchrun --nnodes 1 --nproc_per_node 2  --rdzv_endpoint 30000 examples/finetuning.py 
--enable_fsdp --model_name  model_hf/7B/ --use_peft --peft_method lora --dataset pyql_dataset  
--save_model --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --pure_bf16 
--output_dir PEFT/pyql
```

**Comment by testing-cs** [comment]
problem solved by using ```--rdzv-backend=c10d --rdzv-endpoint=localhost:0```

can you try:

```
torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:0 --nnodes 1 --nproc_per_node 2  examples/finetuning.py 
--enable_fsdp --model_name  model_hf/7B/ --use_peft --peft_method lora --dataset pyql_dataset  
--save_model --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --pure_bf16 
--output_dir PEFT/pyql
```

**Comment by cdhx** [comment]
Thanks for your reply, it works.
