### ISSUE TITLE
ImportError: cannot import name 'get_dataset' from partially initialized module 'llama_recipes.datasets.grammar_dataset.grammar_dataset' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ACBBZ** [facebookresearch/llama-recipes#210]
### 🚀 The feature, motivation and pitch

When I try to train the model, there is an error.
[(llama-recipes) root@tt-deployment-test-6ddcd899cd-dvk58:/code/llama-recipes/src/llama_recipes# python -m llama_recipes.finetuning  --use_peft --peft_method lora --quantization --model_name /code/llama/llama-2-13b-chat-hf/ --output_dir /code/llama/llama-2-13b-chat-lora --dataset alpaca_dataset --batch_size_training 50 --num_epochs 1
Traceback (most recent call last):
  File "/root/miniconda3/envs/llama-recipes/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/miniconda3/envs/llama-recipes/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/code/llama-recipes/src/llama_recipes/finetuning.py", line 29, in <module>
    from llama_recipes.utils import fsdp_auto_wrap_policy
  File "/root/miniconda3/envs/llama-recipes/lib/python3.10/site-packages/llama_recipes/utils/__init__.py", line 5, in <module>
    from llama_recipes.utils.dataset_utils import *
  File "/root/miniconda3/envs/llama-recipes/lib/python3.10/site-packages/llama_recipes/utils/dataset_utils.py", line 8, in <module>
    from llama_recipes.datasets import (
  File "/root/miniconda3/envs/llama-recipes/lib/python3.10/site-packages/llama_recipes/datasets/__init__.py", line 4, in <module>
    from llama_recipes.datasets.grammar_dataset.grammar_dataset import get_dataset as get_grammar_dataset
  File "/root/miniconda3/envs/llama-recipes/lib/python3.10/site-packages/llama_recipes/datasets/grammar_dataset/grammar_dataset.py", line 8, in <module>
    from datasets import load_dataset
  File "/code/llama-recipes/src/llama_recipes/datasets/__init__.py", line 4, in <module>
    from llama_recipes.datasets.grammar_dataset.grammar_dataset import get_dataset as get_grammar_dataset
ImportError: cannot import name 'get_dataset' from partially initialized module 'llama_recipes.datasets.grammar_dataset.grammar_dataset' (most likely due to a circular import) (/root/miniconda3/envs/llama-recipes/lib/python3.10/site-packages/llama_recipes/datasets/grammar_dataset/grammar_dataset.py)](url)

**Comment by fancyerii** [comment]
In line 8 of grammar_dataset.py:
from datasets import load_dataset
It want to use huggingface datasets. But under llama_recipes directory there is also an package named datasets.

I don't find any good solution but rename llama_recipes.datasets to llama_recipes.datasets2 and it works. And you must modify many codes. I use pycharm to refactor the name.

You can also use my diff in https://gist.github.com/fancyerii/d89d4d887b020eec1d756f606c3bc8bf

**Comment by Hanaxx1** [comment]
Have you solved it yet? I had the same problem

**Comment by hanyin88** [comment]
FYI I think there's some issue with torch run environment set up. For me this issue only occurs when runing on multiple GPUs using torchrun.

**Comment by twelfth-star** [comment]
I had the same problem. The reason might be that path `llama-recipes/src/llama_recipes` is included in the environment variable `PYTHONPATH`, so `llama-recipes/src/llama_recipes/datasets`, instead of  `datasets` of huggingface, is imported by `import datasets`. Simply removing `llama-recipes/src/llama_recipes` from `PYTHONPATH` solved my problem.
