### ISSUE TITLE
fsdp with use_fp16 in v100 enviroment, "RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::Half"

### ISSUE THREAD

**Issue by robustor123** [facebookresearch/llama-recipes#284]
### System Info

torch.__version__ : '2.1.0+cu118'
CUDA : 11.5
GPU: V100
4 GPU

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256

torchrun --nnodes 1 --nproc_per_node 4  examples/finetuning.py --enable_fsdp --use_peft --peft_method lora --model_name /home/tica/llama-2-7b/ --fsdp_config.use_fp16 --output_dir tmp

### Error logs

Traceback (most recent call last):
  File "/home/tica/gits/llama-recipes/examples/finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/tica/gits/llama-recipes/src/llama_recipes/finetuning.py", line 228, in main
    results = train(
  File "/home/tica/gits/llama-recipes/src/llama_recipes/utils/train_utils.py", line 83, in train
    loss = model(**batch).loss
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/peft/peft_model.py", line 918, in forward    return self.base_model(
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(                                                                       [801/1844]  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 164, in forward
    return self.checkpoint_fn(  # type: ignore[misc]
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 458, in
checkpoint
    ret = function(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 349, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/peft/tuners/lora.py", line 908, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::Half
Exception raised from addmm_out_cuda_impl at ../aten/src/ATen/native/cuda/Blas.cpp:184 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f2452687617 in /home/tica/miniconda3/envs/llama-rec/lib/python3.10/site-packages/torch/lib/libc10.so)

### Expected behavior

success of training

**Comment by HamidShojanazeri** [comment]
@robustor123 unfortunately BF16 is not supported on v100, you would need a newer GPU. Its supported on A10, A100s.

**Comment by adhiiisetiawan** [comment]
thanks for answer, I debugging it for 6 hours and just got the answer in this issue

**Comment by nvijayrania** [comment]
@HamidShojanazeri: I'm facing the same issue on v100. I've explicitly set `pure_bf16` to false and trying to use mixed_precision from https://github.com/facebookresearch/llama-recipes/blob/38df368a70c292db6e42e0f275139678497fd896/src/llama_recipes/finetuning.py#L149 , but it throws the following error
**_RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::Half_**

- If I set use_fp16=True, pure_bf16=False, the above run fails with this error.
- If I set use_fp16=True, pure_bf16=False, mixed_precision=None, the run succeeds but it trains the model in full precision.
Is fp16 with mixed precision not supported for llama-recipe?
