### ISSUE TITLE
fp16 Training not working as expected

### ISSUE THREAD

**Issue by farris** [facebookresearch/llama-recipes#36]
Hi, I'm attempting to finetune 7b on my Nvidia-DGX server. It has 8 V100 GPU's (16gb) each. Because these are older GPU's they do not have `bf16` support , moreover I cannot use `--quantize` across multiple GPU's, so I can only do `fp16` training (`fp32` causes OOM). 

Even after updating `configs/training.py` and `configs/fsdp.py` , `use_fp16` -> `True`, I cannot get `fp16` to work. Below is the error log:

```yaml
Traceback (most recent call last):
  File "script_name.py", line 237, in <module>
    fire.Fire(main)
  File "/path/to/library/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/path/to/library/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/path/to/library/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "script_name.py", line 220, in main
    results = train(
  File "/path/to/project/utils/train_utils.py", line 91, in train
    outputs = model(**batch)
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/project/peft/peft_model.py", line 947, in forward
    return self.base_model(
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/transformers/models/llama/modeling_llama.py", line 810, in forward
    outputs = self.model(
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/transformers/models/llama/modeling_llama.py", line 698, in forward
    layer_outputs = decoder_layer(
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 165, in forward
    return self.checkpoint_fn(  # type: ignore[misc]
  File "/path/to/python/dist-packages/torch/utils/checkpoint.py", line 251, in checkpoint
    return _checkpoint_without_reentrant(
  File "/path/to/python/dist-packages/torch/utils/checkpoint.py", line 432, in _checkpoint_without_reentrant
    output = function(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/transformers/models/llama/modeling_llama.py", line 413, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/transformers/models/llama/modeling_llama.py", line 310, in forward
    query_states = self.q_proj(hidden_states)
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/peft/tuners/lora.py", line 823, in forward
    self.lora_A[self.active_adapter](self.lora_dropout[self.active_adapter](x))
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/python/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
```

Any ideas what I can do to fix this? Perhaps I can avoid this altogether if I could get `--quantize` to work across multiple gpu's however that raises the error:

```yaml
ValueError: .to is not supported for 4-bit or 8-bit models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct dtype.
```
Any help would be much appreciated! Thank you 😄

**Comment by HamidShojanazeri** [comment]
Thanks 
Using PEFT+FSDP or Pure FSDP as follows I have not been able to repro it/ can you pls give it a try to the followings?
```
torchrun --nnodes 1 --nproc_per_node 8  llama_finetuning.py  --model_name Path/to/7B --use_peft --peft_method lora --use_fp16 --output_dir peft-7b-lastpatch_fp16 --enable_fsdp
```

pure FSDP

```
torchrun --nnodes 1 --nproc_per_node 8  llama_finetuning.py  --model_name .Path/to/7B   --use_fp16 --output_dir peft-7b-lastpatch_fp16 --enable_fsdp --pure_bf16 False
```

**Comment by farris** [comment]
@HamidShojanazeri Thanks a lot for your help, after installing the newest nightly build (didn't do that before 😅 ) and pulling the latest changes - everything is working smoothly... each GPU is only using 50% of its memory as well so the memory utilization is much better.

Can I ask however why it is not recommended to use `fp16`... jw conceptually

**Comment by chauhang** [comment]
@farris V100s do not support bf16 but fp16 should work fine.

**Comment by HamidShojanazeri** [comment]
@farris great to hear things are working now. BF16 usually yield better quality results without much issue, where FP16 in large models may run into some scaling issues (determining right scale parameter). Thats about it otherwise, it works usually in many scenarios.

**Comment by hdnh2006** [comment]
For those who are having the same problem as me, I was getting the same error and I changed:
```
model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
```
for
```
model =LlamaForCausalLM.from_pretrained(model_id, load_in_4bit=True, device_map=0, torch_dtype=torch.float16)
```
in the [`quickstart.ipynb`](https://github.com/facebookresearch/llama-recipes/blob/1aecd00924738239f8d86f342b36bacad180d2b3/examples/quickstart.ipynb) notebook.

Basically I loaded in 4bit precision. My laptop has a RTX 4060 with 8GB of VRAM.
