### ISSUE TITLE
RuntimeError: Forward order differs across ranks: rank 0 is all-gathering 0 parameters while rank 1 is all-gathering 1 parameters

### ISSUE THREAD

**Issue by kushalj001** [facebookresearch/llama-recipes#78]
### System Info

torch 2.0.1+cu118
cuda 11.8
transformers: 4.31.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I see this error when I run the finetuning script with FSDP + PEFT on 2 A100s. This error goes away when I set the environment variable  `export NCCL_P2P_DISABLE=1`. I wanted to confirm if this is the right way to go about this or if suppressing this error might lead to other bugs in training/finetuning.

### Error logs

```
traceback : Traceback (most recent call last):
    File "/cluster/project/sachan/kushal/llenv/lib64/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "llama_ft.py", line 178, in main
      results, eval_preds = train(
    File "/cluster/project/sachan/kushal/llama-exp/llama_train_utils.py", line 89, in train
      outputs = model(**batch, labels=batch["input_ids"])
    File "/cluster/project/sachan/kushal/llenv/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
      return forward_call(*args, **kwargs)
    File "/cluster/project/sachan/kushal/llenv/lib64/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 739, in forward
      args, kwargs = _pre_forward(
    File "/cluster/project/sachan/kushal/llenv/lib64/python3.8/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 409, in _pre_forward
      state._exec_order_data.record_pre_forward(handles, module.training)
    File "/cluster/project/sachan/kushal/llenv/lib64/python3.8/site-packages/torch/distributed/fsdp/_exec_order_utils.py", line 180, in record_pre_forward
      self._check_order(handles_key, is_training)
    File "/cluster/project/sachan/kushal/llenv/lib64/python3.8/site-packages/torch/distributed/fsdp/_exec_order_utils.py", line 243, in _check_order
      raise RuntimeError(
  RuntimeError: Forward order differs across ranks: rank 0 is all-gathering 0 parameters while rank 1 is all-gathering 1 parameters

```

### Expected behavior

The code should run without the error while running distributed finetuning.

**Comment by HamidShojanazeri** [comment]
@kushalj001 I am not able to repro the issue on my end, can you pls make sure you are using PT nightlies in case of using FSDP+PEFT. Also pls share more details/ a repro.

**Comment by HamidShojanazeri** [comment]
@kushalj001 from issue #83 can you pls confirm if this issue is resolved?
